### ISSUE TITLE
Issue KeyError: 'product_name'

### ISSUE THREAD

**Issue by waldirio** [waldirio/satellite6_reports#11]
Facing issues when running the script to collect info

```
# complete_hypervisor_content-host_report/complete_hypervisor_content-host_report.py

    Script in 3 Phases
        1. Collect the whole Content Host info from Satellite and filter only virt-who-*
        2. Process all Hypervisors (virt-who-*) and Content Hosts running on the TOP of each one
        3. Generate a huge CSV file with the entitlement information

/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
## Phase 1 (480 Hypervisors): 2019-03-05 17:37:01.295231
## Phase 2: 2019-03-05 17:37:16.676509
Traceback (most recent call last):
  File "complete_hypervisor_content-host_report/complete_hypervisor_content-host_report.py", line 171, in <module>
    main()
  File "complete_hypervisor_content-host_report/complete_hypervisor_content-host_report.py", line 163, in main
    generate_report()
  File "complete_hypervisor_content-host_report/complete_hypervisor_content-host_report.py", line 142, in generate_report
    check_content_host()
  File "complete_hypervisor_content-host_report/complete_hypervisor_content-host_report.py", line 110, in check_content_host
    aux = hypervisor_name, subscription_name, content_host_name, ch_entitlement['product_name'].replace(",", "")
KeyError: 'product_name'
```

**Comment by waldirio** [comment]
Fixed
